version: '2'

services:
  web_app_frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - http_proxy
        - https_proxy
    container_name: web_app_frontend
    environment:
      - HTTP_PROXY=${http_proxy}
      - HTTPS_PROXY=${https_proxy}
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
    ports:
      - 9000:9000
    volumes:
      - ../:/app